apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnet-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet-service
  template:
    metadata:
      labels:
        app: dotnet-service
    spec:
      containers:
        - name: dotnet-service
          image: {{ .Values.dotnetservice.image }}
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dotnet-service
spec:
  selector:
    app: dotnet-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
